[package]
name = "try_os"
version = "0.1.0"
authors = ["Bobby Rong <rjl931189261@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
